import React from "react";
import { useGetGroupProductQuery } from "@/redux/api/baseApi";
import { Link, useParams } from "react-router-dom";
import { TProducts } from "@/types";
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import useNav from "@/hooks/UserNav";

const SingleProduct: React.FC = () => {
    // Using useParams hook to get the category_id from the URL
    const { id: category_id } = useParams<{ id: string }>();
    useNav("Catygory Products");

    // Using the custom hook generated by RTK Query to fetch data
    const {
        data: response,
        isLoading,
        error,
    } = useGetGroupProductQuery(category_id as string);

    // Handle loading state
    if (isLoading) {
        return (
            <div className="flex justify-center items-center h-screen">
                <p className="text-3xl text-center text-yellow-500 my-2 font-bold">
                    Loading....
                </p>
            </div>
        );
    }

    // Handle error state
    if (error) {
        return (
            <div className="flex justify-center items-center h-screen">
                <p className="text-3xl text-center text-red-500 my-2 font-bold">
                    Error loading data. Please try again later.
                </p>
            </div>
        );
    }

    // Ensure response is valid and handle data
    const products = response?.data || []; // Access the `data` property of the response

    return (
        <div className="bg-amber-50 py-4 md:py-8 lg:py-8 px-5 ">
            <div className=" mt-10 max-w-screen-lg mx-auto ">
                <div className="container mx-auto py-8">
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-10">
                        {products?.map((product: TProducts) => (
                            <Card className="w-full border-2 border-orange-800 text-black p-3 shadow-orange-950 bg-gradient-to-t from-amber-200 to-transparent">
                                <img
                                    src={product?.image}
                                    className="object-contain max-h-[250px] w-full mb-2 "
                                    alt=""
                                />
                                <CardHeader className="p-0">
                                    <CardTitle className="mb-2">
                                        {product?.name}
                                    </CardTitle>
                                    <CardDescription>
                                        <span className="font-semibold">
                                            Description:
                                        </span>{" "}
                                        {product?.description.substring(0, 35)}
                                        ...
                                    </CardDescription>
                                </CardHeader>
                                <CardContent className="grid grid-cols-2 gap-1 p-0 mb-2">
                                    <p className="text-md font-semibold">
                                        Brand:{" "}
                                        <span className="text-base">
                                            {product?.brand.substring(0, 3)}
                                        </span>
                                    </p>
                                    <p className="text-md font-semibold">
                                        Price:
                                        <span className="text-base">
                                            {product?.price}
                                        </span>
                                    </p>
                                    <p className="text-md font-semibold">
                                        Rating:
                                        <span className="text-base	">
                                            {" "}
                                            {product?.rating}
                                        </span>
                                    </p>
                                    <p className="text-md font-semibold">
                                        Stock:
                                        <span className="text-base	">
                                            {product?.stock}
                                        </span>
                                    </p>
                                </CardContent>
                                <CardFooter className="p-0">
                                    <Link
                                        className="font-bold p-0 uppercase border-2 hover:bg-white hover:text-orange-900 border-orange-900 bg-orange-500 w-full text-center py-1"
                                        to={`/cart/${product?._id}`}
                                    >
                                        Detailed view{" "}
                                    </Link>
                                </CardFooter>
                            </Card>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default SingleProduct;
